### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by buonincontrigi** [Apipa169/Assistant-Relay-for-Hassio#1]
Hi, i have raspberry pi 3b with hassio, , I'm trying to install this addon, only it gives me the following errors:

`
19-11-06 21:57:34 INFO (SyncWorker_7) [hassio.docker.addon] Start build 6a3d001f/armv7-addon-assistant_relay:0.5.4
19-11-06 21:59:18 ERROR (SyncWorker_7) [hassio.docker.addon] Can't build 6a3d001f/armv7-addon-assistant_relay:0.5.4: The command '/bin/ash -o pipefail -c wget https://github.com/greghesp/assistant-relay/releases/download/v3.0.3/release.zip && unzip release.zip && rm release.zip && sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/helpers/server.js && sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/helpers/assistant.js && sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/helpers/auth.js && sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/routes/index.js && sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/routes/server.js && sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/bin/www && sed -i -e 's#./bin/config.json#/data/config.json#g' /assistant_relay/routes/server.js && sed -i -e 's#../bin/audio-responses/#/data/audio-responses/#g' /assistant_relay/helpers/server.js && sed -i -e 's#../bin/audio-responses/#/data/audio-responses/#g' /assistant_relay/routes/server.js && sed -i -e 's#bin/audio-responses/#/data/audio-responses/#g' /assistant_relay/helpers/server.js && npm i' returned a non-zero code: 1`

**Comment by Apipa169** [comment]
Thanks for opening this issue. I’ll find out what is happening and coming back to you.

**Comment by Apipa169** [comment]
It seems to be an issue on armv7 installations. Working on it..

**Comment by Apipa169** [comment]
version 0.5.5 works on my test-pi now.

@buonincontrigi Can you try it again?
