### ISSUE TITLE
I don´t get it working

### ISSUE THREAD

**Issue by marschallphilipp** [Apipa169/Assistant-Relay-for-Hassio#10]
**Describe the bug**
I installed the add-on and did all the steps mentioned in instructions in browser.
I´m not sure if I must do anything regarding the "device registration" step? This is one of the 5 steps but the site should only be opened because it´s needed later. Then you say once step 5 is done go back. Hence device registration hasn´t be done!?

Is there any need for opening ports in the router? Does it need port 443 for communicating with the Google API or port 80? Internally my home assistant is running without SSL on 192.168.1.102:8123 (so AR on port 3000). From the internet I have an own domain an it is running with SSL and port 8123 is opened in router to the internet.

When I test the AR in the Web UI in Sandbox I get a red "X" when executing the querry.

Hassio version: Home Assistant 0.102.1
System: Hass.io on Raspberry Pi3 B

**Comment by Apipa169** [comment]
You don't have to do the device registration. You only have to follow it until step 5 and go back to AR as you already did,

There is no need to expose HA or a Google device the the open internet, so please don't forward ports for it!

What is the error in the log when you try the sandbox?

**Comment by marschallphilipp** [comment]
Thanks for the fast feedback!
It´s working now! First I took an account where no Google Homes where connected to and then I forgot enabling the API in the project in a different account.
Works great now. Thanks a lot for the great add-on!

**Comment by Apipa169** [comment]
You’re welcome! Happy to hear it works now!
