### ISSUE TITLE
Best method to update?

### ISSUE THREAD

**Issue by theCheek** [Apipa169/Assistant-Relay-for-Hassio#11]
**Describe the bug**
When I click on update in the hass.io addon, nothing happens

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
Hassio version: 0.102.3
System: Docker in Ubuntu

**Additional context**
Getting the following error in Hassio logs:
19-12-10 05:27:41 INFO (SyncWorker_25) [hassio.docker.addon] Start build 6a3d001f/amd64-addon-assistant_relay:0.7.2
19-12-10 05:27:41 ERROR (SyncWorker_25) [hassio.docker.addon] Can't build 6a3d001f/amd64-addon-assistant_relay:0.7.2: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile")
19-12-10 05:28:41 INFO (SyncWorker_36) [hassio.docker.addon] Start Docker add-on 6a3d001f/amd64-addon-assistant_relay with version 0.5.5

**Comment by Apipa169** [comment]
Thanks for opening an issue.

- To which version do you want to update?
- Does anything appear in the Hass.io logs when you clicked update?

**Comment by Apipa169** [comment]
Looks like you are running one of the first releases. I haven’t had any issues updating myself, but it looks like you do.

The newer version is using a complete image instead of building it on every hass.io installation locally. Therefore a dockerfile is not required anymore, but your system is still looking for it.

Can you reinstall? You have to do the setup again, but if you still have the Json file from google you should be up and running again in a few minutes.

**Comment by theCheek** [comment]
Sure thing, just reinstalled now. I can't access the setup page as I'm at the office and using Nabu Casa, so the 'open web gui' buttom tries to open myaddress.nabu.casa:3000 
I could workaround by bringing back my old port forwards but will wait till I get home instead. Thanks for your work mate 👍

**Comment by Apipa169** [comment]
Yeah, it is better to keep the ports closed. I'm working on Ingress support (#5) to make it available via HA and Nabu Casa, but it won't be soon. 

On the other hand, you'll only need the GUI during the setup. Commands are always send via the local network.

**Comment by theCheek** [comment]
Actually left work a bit early cuz I wanted to get this final puzzle sorted :)

Seems to be working, however my results are not as expected. I'm trying to get the 'good morning' routine to run, but when testing with developer tools --> services, with rest_command.assistant_converse and service data set to command: tell me a joke then my google homes just say "broadcast from <my real name>, tell me a joke". The weird thing is that sometimes it actually says "broadcast from <my real name>, <joke>" as in it actually tells me the joke. Any idea what is going on here?

FYI my setup for assistant_converse is:
```
rest_command:
  assistant_converse:
    url: http://192.168.10.60:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"theCheek", "converse":true}' 
```

**Comment by Apipa169** [comment]
Ah, good news you have the add-on running again!

I haven’t used the converse option a lot, but it sounds like this is a Google issue. And unfortunately it keeps telling “broadcast from x”.

**Comment by theCheek** [comment]
Yeah its really weird as I can't reproduce the error consistently. 

Do you think the username has something to do with it? When setting up the google console i used 'theCheek' as a username but that doesn't correspond to the name Google Assistant has for me. Or is the username completely seperate? 

Sorry if I am cluttering up an already solved issue here with another one!

**Comment by Apipa169** [comment]
The username does not matter. This is the name stored in the config of Assistant Relay. 

I can't test the converse mode now as I'm at work. But this has nothing to do with the add-on an I think neither with Assistant Relay.
