### ISSUE TITLE
Node Red - Send Command example

### ISSUE THREAD

**Issue by SurfingSpider** [Apipa169/Assistant-Relay-for-Hassio#13]
First of all thank you for including a node red example of how to get broadcast working.  That was extremely useful. getting that to work now I am trying to do something different I was hoping you could help with.

I am trying to send a command not a broadcast. I want to send the Command "Play BBC Radio 6music on living room speaker". But cant get it to work (broadcast works fine). I think it will just be my formatting. Could you help with what should be in the function node?

Eventually I want to send the command "Turn off bluetooth on living room speaker", but that might  be a step to far. So I was starting simpler. trying to do a voice command that I know should work.

This is the contents of the function node....

> msg.message = msg.payload;
> msg.payload = {
>     "name": "Username",
>     "command": "Play Radio 6music Living Room Speaker"
> };
> msg.headers = {};
> msg.headers['Content-Type'] = 'application/json';
> return msg;

This is my current flow export.....
`[{"id":"d2efaebe.75757","type":"delay","z":"e226f3b0.04e3f","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"10","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":840,"y":1020,"wires":[["86090342.52b76"]]},{"id":"f40ade86.199e3","type":"http request","z":"e226f3b0.04e3f","name":"post","method":"POST","ret":"obj","paytoqs":false,"url":"http://192.168.0.40:3000/assistant","tls":"","persist":false,"proxy":"","authType":"","x":1270,"y":1020,"wires":[["58e9c9cf.0a08f8"]]},{"id":"86090342.52b76","type":"function","z":"e226f3b0.04e3f","name":"set payload and headers","func":"msg.message = msg.payload;\nmsg.payload = {\n    \"name\": \"Username\",\n    \"command\": \"Play Radio 6music Living Room Speaker\",\n    \"converse\": true\n};\nmsg.headers = {};\nmsg.headers['Content-Type'] = 'application/json';\nreturn msg;","outputs":1,"noerr":0,"x":1070,"y":1020,"wires":[["f40ade86.199e3"]]}]]`

**Comment by Apipa169** [comment]
I think you can’t do that. The Google Assistant SDK is limited and does not allow all commands.. 

What is the response? You can find the audio responses in the GUI.
