### ISSUE TITLE
Cannot read property 'access token' of undefined.

### ISSUE THREAD

**Issue by elserge82** [Apipa169/Assistant-Relay-for-Hassio#15]
The first time I installed your plugin. I created a new user and everything was successful.Few days later the plugin stopped with the following error:
getting metadata from plugin failed with error: Cannot read property 'access token' of undefined.
I added a new user and everything went fine. Few days later , the plugin no longer working with the same error. Not sure what caused it but whenever I need a relay command it ended unsuccessful. :)

My platform consist of Hassio docker on Raspbian.
Thank you. And hopefully with your help I can sort this out .

**Comment by Apipa169** [comment]
Thanks for opening an issue.

I don't think this is related to this ad-on. Actually this add-on is just an image with Assistant Relay pre installed. Could you please reopen your initial issue?

**Comment by elserge82** [comment]
I see. Thank you for your time.:)

**Comment by Apipa169** [comment]
You're welcome!
