### ISSUE TITLE
Service not found when calling rest_command.assistant_broadcast

### ISSUE THREAD

**Issue by snook** [Apipa169/Assistant-Relay-for-Hassio#16]
When using the Assistant Relay sandbox commands work fine, they broadcast to my speakers or I can turn lights on and off etc. However I can not use rest_command.assistant_broadcast from Hassio.

When I go to Developer Tools in HA and go to the services tab, rest_command.assistant_broadcast is not listed in the dropdown. When I enter rest_command.assistant_broadcast as the service and enter "command: Testing" into the Service Data and press the Call Service a popup alert in the bottom left appears and says: 

`Failed to call service rest_command/assistant_broadcast. Service not found.`

This is my first time installing this. I've tried uninstalling and re-installing the addon and restarting the server.

Assistant Relay: 0.7.3
Hassio version: 0.104.1
System: HassOS 3.8

Thank you

**Comment by Apipa169** [comment]
What is your configuration.yaml? I only need to know what is in “rest_command:”

**Comment by snook** [comment]
Oh my gosh, thank you I forgot to add that. Still new to HA and was glazed over them thinking those were alternate ways to call commands since I was specifically looking for the automation portion. Of course it works now :)

**Comment by Apipa169** [comment]
Great :)
