### ISSUE TITLE
Can’t install on raspberry pi zero W

### ISSUE THREAD

**Issue by jon6fingrs** [Apipa169/Assistant-Relay-for-Hassio#17]
Hi, I just installed hass.io on an old raspberry pi zero W. I added the github and see google relay and google relay beta in the hass.io store, but the option to install them is grayed out and I get the following error:

20-01-23 01:25:42 ERROR (MainThread) [hassio.addons] Add-on 6a3d001f_assistant_relay not supported on that platform
20-01-23 01:25:45 ERROR (MainThread) [hassio.addons] Add-on 6a3d001f_assistant_relay not supported on that platform

Is this addon not compatible with the raspberry pi zero W at all? Or is there a way to bypass this?

Thanks

**Comment by Apipa169** [comment]
I’m not sure if it will run on a raspberryPi zero. I do not own one so I can’t test it and can’t create a stable image.

**Comment by jon6fingrs** [comment]
Doing a little more research, seems it’s not possible. The raspberry pi zero is armv6.

**Comment by Apipa169** [comment]
It should be possible to create an image, but I can’t as I don’t have a Pi zero. :(
