### ISSUE TITLE
How can i make this visible in Google home on my phone

### ISSUE THREAD

**Issue by sniperxnl** [Apipa169/Assistant-Relay-for-Hassio#18]
I have installed everything on the hassio and google account.

But how can i make the devices visible on my phone and visible for the google speaker

**Comment by Apipa169** [comment]
This addon is not made to expose devices to google. This can be used by setting up the built in Google integration. This can be done manually or via Nabu Casa. The last one is the easiest way and you are also supporting the development of Home Assistant!
