### ISSUE TITLE
Access to Google Response Text in Home Assistant Automations

### ISSUE THREAD

**Issue by CraigHoffmann** [Apipa169/Assistant-Relay-for-Hassio#21]
Hi Apipa169, thanks for the Assistant Relay for Hassio.  I have it installed and working, very easy setup.

When using the Sandbox page, after sending a request to google the response is shown as text in a popup window, and also there is a link to the audio response.  There is also a history of these responses/audio on the assistant relay home page.

I was wondering if there is a way to get the response text string (latest response only) available to home assistant automations possibly as a sensor value or similar?

**Comment by Apipa169** [comment]
Home Assistant can't do anything with the response at the moment via the RESTful command. There is a RESTful sensor, but you don't want to send commands constantly, so this is no option. Implementing this into the add-on means it need to be added to the original Assistant Relay, which will be just for a few users.

But if you are using Node Red it can be done easily. The response from AR is as follows. The response can be used in an other flow. Or if you want to have it in HA you can send it via MQTT to HA for example.

```javascript
{
    "success": true, // Or false
    "response": "", // Contains the text response from Google Assistant if applicable
    "audio": "/server/audio?v=1581510182698", // A URL to the audio response from Google Assistant
    "error": "Error Message" // Only shown if success if false
}

**Comment by CraigHoffmann** [comment]
Thanks for the feedback.  I'll have a look into node-red... haven't needed it for anything before.

Would node-red be installed on my hassio raspberry pi, or can it be on another device?

Also when you say "Or if you want to have it in HA you can send it via MQTT to HA for example."  Do you mean that the MQTT is sent using node-red or can the MQTT be sent directly from Assistant Relay somehow?

**Comment by CraigHoffmann** [comment]
Hi Apipa169, following your lead with suggested ideas above I have found the node-red was already an addon in hassio.  I have installed that and managed to get MQTT commands that send/receive to the Google Assistant Relay addon.

I now just need to do the extra steps to process the response and send to the targetted cast device.

Thanks for the help.

Cheers,
Craig

**Comment by Apipa169** [comment]
Assistant Relay does not have MQTT support, but NodeRed does. NodeRed also supports cast, so you won't need HA to do that for you.

If you are new to NR, this is a great start: https://www.youtube.com/watch?v=SuoSXVqjyfc&t=135s

**Comment by Apipa169** [comment]
There is a very easy solution available now via Node Red. If you update the Node Red add-on to the newest version you can now create entities (sensor, binary and switch) in Home Assistant! Only extra requirement is installing https://github.com/zachowj/hass-node-red

If you add this sensor via Node Red and add it to the flow which is available as example in this repository you should have what you need!

**Comment by marcospg75** [comment]
Hello... I found this thread and is just what I was looking for... the cuestion is that I have a Thermostat that's only supported in Google Home and I want to send a command (with Assisstant Retay) to query it wich termperature is set and put this information in a sensor.
If I send this question... the answer si something like this:
{
    "response":"",
    "audio":"/server/audio?v=1606031406209",
    "success":true
}

I expected to have in "response" the text of the audio (something like: "the temperature in the Thermo device is 23C",  but always receive "".
Is there a way to get the Speech To Text of the answers? 
I'm using the latest version of Home Assistant with Node Red and Assistant Relay Add-ons

**Comment by georgejung** [comment]
I am interested in the speech to text as well. I have a Schlage encode wifi lock and can ask google, via assistant relay of course, if my door is locked. I get back an audio file that tells me the door is unlocked, or locked. Unfortunately tt doesn't have a text response and I would like to be able to use this to update a binary switch of whether my door is locked or unlocked...
