### ISSUE TITLE
Broadcast just works for a couple of times only

### ISSUE THREAD

**Issue by Kitser** [Apipa169/Assistant-Relay-for-Hassio#22]
I installed this addon and I got it to work. It works great! Thanks!
But I wanted the broadcast service to use not my name, but use "Broadcast message from Home Assistant" instead.
So I made an extra Gmail account which has "Home Assistant" as the first name. I repeated all the steps for this account.
When I finished the configuration, I set up my Google Home to use the newly created Gmail account.
Then I deleted the user "assistant" in the Assistant Relay config page, which I used for my personal Gmail account.
And created a new user and used the json file from the newly created Gmail account with "assistant" as username again.
When I tested this the Google Home plays the broadcast with "Home Assistant". So that's great! 
But after 1 or 2 times sending a broadcast message it stopped working. Every now I then I can send a broadcast message again and the Google Home plays it. But after one time playing the broadcast message, it stops working. It seems to be random.
I repeated the setup process multiple times, I used different usernames in the config page and my Home Assistant yaml, made another Gmail account with "Home Assistant" as the first name, double-checked all the settings in https://console.developers.google.com/ but I can't find what I'm doing wrong.

When I change it back to my personal Gmail account everything works just fine.

What can this be?

**Comment by Apipa169** [comment]
Thanks for opening an issue!

What’s in the log of the addon at the moment it doesn’t work?

**Comment by Kitser** [comment]
Do you mean the log in the addon? That's 

`0|www  | POST /server/checkUpdate 200 273.250 ms - 1107
0|www  | v3.2.0
0|www  | GET /server/version 200 15.436 ms - 20
0|www  | Conversation Complete
0|www  | POST /assistant 200 1682.665 ms - 70
0|www  | Conversation Complete
0|www  | POST /assistant 200 1605.644 ms - 70
`

**Comment by Apipa169** [comment]
Is this the log when it doesn’t work? The log you just posted looks fine to me.

**Comment by Kitser** [comment]
Yes. When I played a broadcast message the Google Home doesn't plays it. I tried again and this is the log:
`0|www  | Conversation Complete
0|www  | POST /assistant 200 1533.925 ms - 70
`

**Comment by Apipa169** [comment]
I have the exact same set up running without any issues. Strage it does not work all the time for you.

If you send a command, can you check if you see it at https://myactivity.google.com/myactivity? This needs to be checked on the account you have created of course.

**Comment by ChrisJohns-me** [comment]
I’ve got the same issue, but after Broadcasting through the iOS Google Assistant app m, I discovered that it’s a problem with the Google Broadcast:
[https://www.reddit.com/r/googlehome/comments/f1caz6/broadcast_limit_or_bug/](https://www.reddit.com/r/googlehome/comments/f1caz6/broadcast_limit_or_bug/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by Kitser** [comment]
> I have the exact same set up running without any issues. Strage it does not work all the time for you.
> 
> If you send a command, can you check if you see it at https://myactivity.google.com/myactivity? This needs to be checked on the account you have created of course.

I just tested it again via the sandbox. It worked 4 times and then it stopped again.
At the myactivity page I see this:

![](https://i.imgur.com/MDsmSMy.png)

So it seems to work okay according to this page. But it doesn't  :-(

**Comment by Apipa169** [comment]
As far as I know this should show every try. Can you confirm you have tried it a few times but it is only showing once?

**Comment by Kitser** [comment]
> As far as I know this should show every try. Can you confirm you have tried it a few times but it is only showing once?

That's right. It only shows once. I tried it a few times.

But with my personal account it shows only once as well when I broadcast multiple times. And with that account it works every time.

**Comment by Apipa169** [comment]
Let's continue this in the issue you opened at the Assistant Relay repository.

https://github.com/greghesp/assistant-relay/issues/158

**Comment by peppeschizzo** [comment]
Same problem for me
