### ISSUE TITLE
"Use the Menu to Sign In"

### ISSUE THREAD

**Issue by databoy2k** [Apipa169/Assistant-Relay-for-Hassio#24]
**Describe the bug**
I have followed all of the steps as outlined. I have even managed to add my home assistant user. However, at all times I am given a message to use the menu to sign in. When on the assistant relay homepage with all of the test actions and the play buttons, I have the same message appearing and pressing any play button causes the assistant voice on my computer to say, " use the menu to sign in."

**Comment by Apipa169** [comment]
Did you login after uploading the JSON file?

**Comment by databoy2k** [comment]
I did. And copied and pasted the key that the login generated.

**Comment by Apipa169** [comment]
You might have downloaded the wrong json file. 

Can you repeat these steps? (Just what is under "configuring credentials"
https://greghesp.github.io/assistant-relay/docs/getting-started/configuration#configuring-credentials

**Comment by databoy2k** [comment]
After a bit of a battle I think I have it working. Not sure what I did right, but eventually it just started working. closing this.
