### ISSUE TITLE
Internal IP changes between (multiple?) restarts

### ISSUE THREAD

**Issue by kalimaul** [Apipa169/Assistant-Relay-for-Hassio#26]
**Describe the bug**
The internal IP of Assistant Relay changed, making my related automations broken.

**To Reproduce**
Not sure about exact repro. I updated the supervisor and homeassistant itself, which included several system restarts. Somewhere along the way Assistant Relay got a new internal IP.

**Expected behavior**
Have a static IP or hostname I can reference in my homeassistant and appdaemon scripts.

**Screenshots**
N/A

**System (please complete the following information):**
(after update)
Hassio version: 3.11 prod
Supervisor: 201

**Additional context**
N/A

**Comment by Apipa169** [comment]
Why are you not connecting via the IP of the host?

**Comment by kalimaul** [comment]
My bad! I tried using the hostname and that didn't work - I didn't realize using the external IP will. Thanks!
