### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by GregSumner** [Apipa169/Assistant-Relay-for-Hassio#28]
**Is your feature request related to a problem? Please describe.**
I'd like to try this add-on with my NanoPi NEO2 but Assistant Relay currently says unsupported in the store. I believe an aarch64 build would allow install through the store.

**Describe the solution you'd like**
An aarch64 docker build/support to install on aarch64 through the add-on store.

**Describe alternatives you've considered**
Not aware of alternatives

**Additional context**
Thanks for the work on the add-on!

**Comment by Apipa169** [comment]
Can you try to install the normal version now? (not the beta, that won't work at all)

I'm  not sure if it will work as I don't have any device to test it on.

**Comment by GregSumner** [comment]
Hi, it looks like my issue ended up being the Orange Pi config I was using in hassio being depricated. I swapped over to the odroid n2 config and the normal version installed without issue. So, it works thanks, but I guess I can't test this build now.
