### ISSUE TITLE
Unable to install the beta version on raspberry pi 4

### ISSUE THREAD

**Issue by Weegle99** [Apipa169/Assistant-Relay-for-Hassio#29]
**Describe the bug**
Unable to install beta version on home assistant raspberry pi 4

**To Reproduce**
1. Type "assistant relay" in the addon store
2. See that the beta version is not available

**Expected behavior**
Is it possible to install the beta version on raspberry pi 4 ? If not, why ?

**Screenshots**
![image](https://user-images.githubusercontent.com/20414450/77559784-e306c480-6ebc-11ea-86d9-5a88419cb566.png)

**System (please complete the following information):**
Hassio version : 0.107.6
System : I don't know how to find that

**Additional context**
Awesome work ! :)

**Comment by Apipa169** [comment]
Thanks!

Currently it’s not supported because I can’t create the image in the Docker cloud automatically. This means I have to create Raspberry images manually on a RPI. That is why I have decided to support only a normal release on RPI.

**Comment by Apipa169** [comment]
By the way, the beta does not have additional functionality for a Home Assistant installation as casting is supported by HA itself.

**Comment by Weegle99** [comment]
Oh I didn't know that, does it mean that I can cast a Netflix TV show directly from ha ?

**Comment by Apipa169** [comment]
I don’t think that will work at all. You’ll run into authentication issues and I don’t know how to select a specific episode without doing a lot of configuration.

**Comment by Weegle99** [comment]
Ok thanks for the reply
