### ISSUE TITLE
I can't install the addon

### ISSUE THREAD

**Issue by jumping2000** [Apipa169/Assistant-Relay-for-Hassio#3]
I have problem to install the addon
hass,io 0.102.2
supervisor 192

19-11-25 17:47:16 INFO (SyncWorker_11) [hassio.docker.addon] Start build 6a3d001f/amd64-addon-assistant_relay:0.5.5
19-11-25 17:49:09 ERROR (SyncWorker_11) [hassio.docker.addon] Can't build 6a3d001f/amd64-addon-assistant_relay:0.5.5: The command '/bin/sh -c mkdir /assistant_relay && npm i pm2 -g' returned a non-zero code: 1
19-11-25 17:49:09 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<AddonManager.install() done, defined at /usr/src/hassio/hassio/addons/__init__.py:106> exception=AddonsError()>

**Comment by Apipa169** [comment]
I'm working on an update using a new image. Hopefully this will solve the issue.

I have added the beta of it to this repository. Can you try that one please? 

Note: the beta is currently amd64 only.

**Comment by jumping2000** [comment]
> I'm working on an update using a new image. Hopefully this will solve the issue.
> 
> I have added the beta of it to this repository. Can you try that one please?
> 
> Note: the beta is currently amd64 only.

Hi, the beta solves the issue! Now I can install the addon. thanks

**Comment by Apipa169** [comment]
Great! Thanks for testing. 

When the Raspberry image is ready I can update the add-on. If you switch over to the normal version then you need to reconfigure, but that won't take much time if you keep the OAuth file from Google (in a secure place).

**Comment by Apipa169** [comment]
Released v0.6.3! This release is exactly the same as the bete you tested.
