### ISSUE TITLE
Can't get addon started...

### ISSUE THREAD

**Issue by RedPhantom07** [Apipa169/Assistant-Relay-for-Hassio#30]
Total noob here.  Am I missing something else that needs to be installed along with this plugin?

Followed the instructions to add the repository, and was able to successfully install the addon.

However add-on will not start.  Report from log is:

[FATAL tini (6)] exec docker-entrypoint.sh failed: Exec format error

Running Hass.io on HassOS

**UPDATE: Never mind, I realized i'm running on aarch64 which is not supported.

**Comment by Apipa169** [comment]
Sorry for that! I’m currently unable to add support for Aarch64.
