### ISSUE TITLE
exec docker-entrypoint.sh failed

### ISSUE THREAD

**Issue by bradwallis1** [Apipa169/Assistant-Relay-for-Hassio#31]
Assistant Relay for Hassio will not start

To Reproduce Steps to reproduce the behavior:

Go to Supervisor
Click on Add-on-Store
Install Assistant-Relay-for_Hassio
Click on 'Start'
See error: **[FATAL tini (6)] exec docker-entrypoint.sh failed: Exec format error**
Expected behavior: The add on starts

Screenshots If applicable, add screenshots to help explain your problem.

System (please complete the following information): Hassio version: System: Home Assistant 0.108.6

Additional context Add any other context about the problem here.
![hassio screen](https://user-images.githubusercontent.com/20231731/79685281-9e452380-8205-11ea-8d60-4184356aca96.PNG)

Hassio recently had a big update.

**Comment by Apipa169** [comment]
Sorry! Aarch64 is currently not supported. I’ll update the addon to make it gray in the “store” for aarch64 devices.
