### ISSUE TITLE
Add labels to the add-on images

### ISSUE THREAD

**Issue by guice** [Apipa169/Assistant-Relay-for-Hassio#32]
**Is your feature request related to a problem? Please describe.**

HA add-ons have tables associated with them, `io.hass.*`, which makes it easy to filter out in services such as Portainer. 

**Describe the solution you'd like**

Add `io.hass.*` labels, e.g. `io.hass.type=addon` so they can be auto-filtered by other HA add-ons (e.g. Portainer addon). 

Here's an example add-on:

<img width="1152" alt="Screen Shot 2020-05-27 at 8 51 57 AM" src="https://user-images.githubusercontent.com/205378/83036109-80828f80-9ff7-11ea-924d-358a19cb413d.png">

**Comment by Apipa169** [comment]
Good suggestion! I'll work on that :)

**Comment by Apipa169** [comment]
It's available in the BETA, i'll add it to the normal release when there is an update!
