### ISSUE TITLE
Can't get it installed

### ISSUE THREAD

**Issue by Gordy11Blast** [Apipa169/Assistant-Relay-for-Hassio#33]
**Describe the bug**

**To Reproduce**
1. Go to 'Supervisor, Add-onStore
2. Click on 'Install Assistant Relay for Hassio'

**Expected behavior**
The add on wont to install. I attached the screenshots about the error.

**Screenshots**

**System (please complete the following information):**
Hassio version: 227
System: HassOS 3.13

Here is what I got:

**Comment by Gordy11Blast** [comment]
![Screenshot (569)](https://user-images.githubusercontent.com/66097823/83883290-4dd04980-a711-11ea-93f8-ea172fd40650.png)
![Screenshot (570)](https://user-images.githubusercontent.com/66097823/83883302-4f9a0d00-a711-11ea-9f08-1b1f3b0896ae.png)
![Screenshot (571)](https://user-images.githubusercontent.com/66097823/83883304-4f9a0d00-a711-11ea-8eaf-bf840306791a.png)

**Comment by Apipa169** [comment]
Hello,

The add on should not be in the custom-components folder, you don't need to download anything manually.

Can you take the following steps:

1. Go to Supervisor -> Add-on store
2. Click on the 3 dots in the right top corner and then repositories
3. Add: https://github.com/Apipa169/Assistant-Relay-for-Hassio
4. Close and click on Assistant Relay and then install.

**Comment by Gordy11Blast** [comment]
I’ve try it on a fresh hassio install and got this error:

[cid:image003.png@01D63FE4.BC629900]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Apipa169** [comment]
@Gordy11Blast i have removed your comment because it contained your email address. Also, I wasn’t able to see the attached picture.

**Comment by Gordy11Blast** [comment]
![Screenshot (579)](https://user-images.githubusercontent.com/66097823/84413331-74452780-abde-11ea-8af2-27b7e3d5a14c.png)
Just got this error with a fresh hassio install

**Comment by Apipa169** [comment]
Strange! I just tried to install it on a raspberryPi 3 which worked fine. 

Are there other add-ons you can't install?

**Comment by Gordy11Blast** [comment]
All others have installed without problems.

I'm available to Teamviewer sessions so you can check it on my pc (if you want to)

**Comment by Apipa169** [comment]
Can you try the following steps:
- Add https://addons.community as repository in the add-on store (if you havent done that yet)
- Install Portainer
- Open it and click on Images in the left sidebar
- Make sure "registry" is DockerHub
- Use as image: apipa169/armv7-hassio-assistant_relay:0.7.4
- Click on Pull the image

Let me know how that goes, if you're not running you should be able to run the add-on.

**Comment by Gordy11Blast** [comment]
I dont know why but Portainer is'nt available to download.
s
![image](https://user-images.githubusercontent.com/66097823/84437060-67d2c600-ac02-11ea-8171-8af16d157189.png)
![Screenshot (580)](https://user-images.githubusercontent.com/66097823/84437082-6d301080-ac02-11ea-92d3-a81838bb66ee.png)

**Comment by Gordy11Blast** [comment]
Failure
Get https://registry-1.docker.io/v2/apipa169/armv7-hassio-assistant_relay/manifests/0.7.4: unauthorized: incorrect username or password

![image](https://user-images.githubusercontent.com/66097823/84444317-8095a880-ac0f-11ea-8eda-7972ac0258d8.png)


Thank you very much for your attention with my issue

**Comment by Apipa169** [comment]
Sorry for such a late reply.

I see that the other images on your system have a aarch64 architecture. This means that this addon is not compliant with your system. Sorry for that!
