### ISSUE TITLE
Need to send converse (command) twice

### ISSUE THREAD

**Issue by Dendrowen** [Apipa169/Assistant-Relay-for-Hassio#34]
**Describe the bug**
When sending a command (e.g. turn on table lights) I need to send it two time for the command to be carried out.

**To Reproduce**
1. Go to 'snadbox' tab in the web ui.
2. Sending message with the following payload through POST:
`{
	"command": "turn on table lights",
	"user": "My username",
	"converse": true
}`
3. My Google Nest is telling me I sent a broadcast with the following text: '[ding] broadcast from [my name], broadcast.'
4. Send it again, Google Nest does nothing but table lights turn on.

**Expected behavior**
My table lights turning on the first time

**System (please complete the following information):**
Hassio version: 227 (newest)
System: Raspberry pi

**Comment by Apipa169** [comment]
Is your request in English or did you translated it when creating this issue?

**Comment by Apipa169** [comment]
It has to do with this issue: #27. Closing this one to continue there.

If you set converse to false it will probably go better.
