### ISSUE TITLE
Error to add repository 

### ISSUE THREAD

**Issue by mastria** [Apipa169/Assistant-Relay-for-Hassio#35]
I'm trying to add the repository and I get the message below:

Repostitory structure for 0.7.4 is not compliant

**Comment by Apipa169** [comment]
On what kind of system are you running Hassio?

**Comment by Apipa169** [comment]
And it is also helpful to know when and where the error is shown. 

Thanks!

**Comment by mastria** [comment]
Home Assistant 0.111.4

Home Assistant Community Store
Integration version: 1.1.2

[https://i.ibb.co/gRQfCHf/Anota-o-2020-06-30-123445.png](url)

**Comment by Apipa169** [comment]
This add-on does not work with HACS as this is a total different kind of add-on.

You need to run Hassio to use this add-on. If you run Hass.io please go to Supervisor -> Add-on store and click on the 3 dots.

If you don't run Hass.io you can consider running Assistant Relay directly on your system or in Docker: https://github.com/Apipa169/Assistant-Relay-Docker

**Comment by mastria** [comment]
Ops! Thank you!!!
