### ISSUE TITLE
Never receive token on setup

### ISSUE THREAD

**Issue by tahlequawesome** [Apipa169/Assistant-Relay-for-Hassio#37]
I am hassio on NUC (image install with supervisor, whatever that is called now). I have gone through setup multiple times with regular add-on and beta and get to the same point each time: adding a user.
I enter the username, select the client secret file, and then hit next and am presented with a google sign-in page and another access confirmation page after that after which that tab or window goes away and I am left back at the AR setup tab prompting for a token. I have tried all different browsers including chrome incognito. I have tried just closing the code / token prompt tab and using the system but when I create a request / command in the sandbox I get an error about no auth token.
Any pointer on what I may be doing wrong would be much appreciated.

**Comment by Apipa169** [comment]
Did you see a token after logging in? Otherwise it could be that you did not download the correct file from the google webpage.

**Comment by tahlequawesome** [comment]
I changed the oauth credential consent to "desktop app" and finally received the token after the sign-in and allow app access prompts during add-user. There is no longer an "other" option to select at the application type screen as per the instructions so hopefully this will help anyone else experiencing the same issue.
