### ISSUE TITLE
Update addon to 3.3.2?

### ISSUE THREAD

**Issue by fredamn76** [Apipa169/Assistant-Relay-for-Hassio#38]
Is it possible to update the addon to version 3.3.2 of Assistant Relay?

**Comment by Apipa169** [comment]
This version is still in beta. However the beta version of this add-on is still on 3.2.1b I'm not planning to update it for now.

The developer of AR is working hard on a 4.0 version which will be in the next update, once it is ready for beta testing. When 4.0 is released the normal add-on will be updated as well.

**Comment by Apipa169** [comment]
GAR v4 is now available in HA as beta. Keep in mind that v4 is still under development.
