### ISSUE TITLE
Allow broadcasting to specific devices

### ISSUE THREAD

**Issue by sparkydave1981** [Apipa169/Assistant-Relay-for-Hassio#39]
**Is your feature request related to a problem? Please describe.**
Feature request, not a problem

**Describe the solution you'd like**
Google has announced that you can now broadcast to specific devices. Is it possible to include this functionality with this add-on?

**Describe alternatives you've considered**
None since starting this one, this add-on is awesome.

**Additional context**

https://www.androidpolice.com/2020/08/05/you-can-now-broadcast-messages-to-a-single-google-or-nest-home/

**Comment by Apipa169** [comment]
Great that should finally work! Last time I tried it wasn't working yet.

It might already work. Assistant Relay is sending your input to Google, adding "broadcast" as prefix. What might work is sending: "to [speaker name] hello!".

I'm not able to try it now, but I will do if I'm home. You can also give it a try!

**Comment by sparkydave1981** [comment]
Thanks for the response. I won't be able to test until next week but I will definitely do it then

**Comment by Apipa169** [comment]
It doesn't work on my end. It also doesn't work using my voice. It wouldn't surprise me if Google didn't roll out this feature to the Netherlands (where I live) yet.

**Comment by FuzzyMistborn** [comment]
I just tested and it works to broadcast to a specific room (but not multiple rooms).  Can broadcast to speaker groups too.

**Comment by Apipa169** [comment]
That's great news!

So broadcasting to multiple rooms at the same time is possible if they are in a speaker group.

**Comment by FuzzyMistborn** [comment]
Correct. So you can put "to first floor Hello" and it works if you have a group called first floor. "to kitchen and family room Hello" does not work (goes to kitchen and the message is "and kitchen hello").

**Comment by Apipa169** [comment]
Closing it for now as it works. There might be a better implementation in GAR 4.0.
