### ISSUE TITLE
Empty error popup message and TypeError: Cannot read property 'converse' of undefined

### ISSUE THREAD

**Issue by misosec** [Apipa169/Assistant-Relay-for-Hassio#4]
Hello,
when I try to use sandbox, all I get is empty error popup (just red-white cross) in browser and this error message in hass.io RA addon log:

` POST /server/getConfig 200 22.618 ms - 126
0|www  | POST /assistant 400 25.227 ms - 44
0|www  | TypeError: Cannot read property 'converse' of undefined
0|www  |     at new Conversation (/assistant_relay/node_modules/google-assistant/components/conversation.js:129:34)
0|www  |     at /assistant_relay/helpers/assistant.js:19:38
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)`

Thank you.

**Comment by Apipa169** [comment]
Thanks for opening an issue.

Are you sure you filled in the correct username in the sandbox? This should be identical to the username you entered during the setup. If not it will return this error.

**Comment by misosec** [comment]
Hello,
I did try to add new user with the username I used in the sandbox, it said username already exists, so I think I used the right username.

**Comment by T-GraysonAdams** [comment]
Could this be because you're not passing `"converse": "false"` in the JSON payload?

**Comment by misosec** [comment]
Hello,
this is screenshot:

![Image-001-(20-26-36)](https://user-images.githubusercontent.com/29805226/69887311-97fdeb80-12e6-11ea-9ba0-bb58700d5043.png)

**Comment by Apipa169** [comment]
It looks like Assistant Relay doesn’t like capitals. Can you try to create a user with a new name using only lowercase letters? 

I’ll raise an issue at Assistant Relay later.

**Comment by misosec** [comment]
Hello, 
I restarted everything I could again, and it's working now.
Sorry for 'false alarm'.
