### ISSUE TITLE
Is this repo still updated?

### ISSUE THREAD

**Issue by kebel87** [Apipa169/Assistant-Relay-for-Hassio#40]
Hi @Apipa169 ,

I’ve been using your repo in an Home Assistant installation. I was wondering if you intend on updating it to the latest version of  assistant relay? 

Thanks!

**Comment by Apipa169** [comment]
Absolutely! The intention is to support GAR 4 via this add-on.

**Comment by Apipa169** [comment]
GAR v4 is now available in HA as beta. Keep in mind that v4 is still under development.
