### ISSUE TITLE
Error on installation of addons

### ISSUE THREAD

**Issue by carlba** [Apipa169/Assistant-Relay-for-Hassio#42]
**Describe the bug**
Error on installation of addons

**To Reproduce**
1. Go to https://hassio.local/hassio/addon/6a3d001f_assistant_relay/info
2. Click on install

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1884191/92639516-34283a80-f2dc-11ea-97a7-8db47aee161c.png)

**System (please complete the following information):**
Hassio version:4.13
System: RPI 2

**Comment by Apipa169** [comment]
Can you post the log in supervisor->system?

**Comment by Apipa169** [comment]
I'm closing this issue for now. Feel free to reopen if you still experiencing this issue.
