### ISSUE TITLE
Do i need to change that ip?

### ISSUE THREAD

**Issue by Tomlap123** [Apipa169/Assistant-Relay-for-Hassio#45]
**Describe the bug**
Simple question about this lane:
url: http://192.168.10.2:3000/assistant
do i need to change it?
My google nest mini is not broadcasting right now via the component

**To Reproduce**
1. Go to 'configuration.yaml'

**Expected behavior**
Hear broadcast from the google nest mini.

Hassio version:
Version
245

**Comment by Apipa169** [comment]
You need to change that IP to the ip address of the device where you run Hassio on.

**Comment by Tomlap123** [comment]
Ok soo i did that but something is still not working... Do i need to wory when i get blank card pop out after entering username and importing client_secret?

**Comment by Tomlap123** [comment]
Where i can find the auth code? 
![image](https://user-images.githubusercontent.com/59482532/94251549-f73a8580-ff22-11ea-87fc-802b73dee88c.png)

**Comment by Apipa169** [comment]
The blank pop up should be the login to google. Do you have a popup blocker enabled?

**Comment by Tomlap123** [comment]
No, i will try on other browser.

**Comment by Apipa169** [comment]
Have you followed all of these steps by the way?

https://greghesp.github.io/assistant-relay/docs/getting-started/configuration

**Comment by Tomlap123** [comment]
Now i see there is a difrence. Give me a second.

**Comment by Tomlap123** [comment]
Ok , the problem was me selecting web aplication instead of TV and Limited Input devices.I have openned account sucesfuly. But still cant get broadcast to work...
![image](https://user-images.githubusercontent.com/59482532/94253456-a2e4d500-ff25-11ea-9dd3-f33b83367e6d.png)

**Comment by Tomlap123** [comment]
When i use Sandbox in aplication everything is working.

**Comment by Apipa169** [comment]
I believe the letter b should not be in the payload of the request

**Comment by Tomlap123** [comment]
It is working anyway, but @Apipa169 can i make broadcast say something without "broadcast from *user*" is it possible to turn radio on by this component?

**Comment by Apipa169** [comment]
Glad to hear it works! Unfortunately Google always adds "broadcast from _user_". Google is changing it to "It's from _user_", bit better, but unfortunately not what you want.

I'm not sure if you can turn on your radio, can't promise anything .
