### ISSUE TITLE
armv6l support?

### ISSUE THREAD

**Issue by joech4n** [Apipa169/Assistant-Relay-for-Hassio#49]
**Describe the bug**
When installing the addon, I see `This add-on is not available on your system.` and this error in the supervisor logs:

```
20-10-11 04:12:29 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/Apipa169/Assistant-Relay-for-Hassio repository
20-10-11 04:12:37 INFO (MainThread) [supervisor.store] Load add-ons from store: 68 all - 2 new - 0 remove
20-10-11 04:24:26 ERROR (MainThread) [supervisor.addons] Add-on 6a3d001f_assistant_relay not supported on that platform
20-10-11 04:24:26 ERROR (MainThread) [supervisor.addons] Add-on 6a3d001f_assistant_relay not supported on that platform
20-10-11 04:28:17 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-10-11 04:41:01 ERROR (MainThread) [supervisor.addons] Add-on 6a3d001f_assistant_relay not supported on that platform
```

**To Reproduce**
1. Try to install add-on.

**Expected behavior**
Add-on successfully installed.

**Screenshots**
N/A

**System (please complete the following information):**
Hassio version: 247
System: Raspberry Pi 1 B

**Additional context**
Is there a way to get this add-on to work on my system?

**Comment by Apipa169** [comment]
The raspberry 1 is not and won't be supported. 
I'd consider an upgrade, you will mention a lot of improvement in performance in Home Assistant, apart from this add-on.
