### ISSUE TITLE
Broadcast not working

### ISSUE THREAD

**Issue by dheuts90** [Apipa169/Assistant-Relay-for-Hassio#53]
Broadcast is not working. Everything looks ok, but I don't hear anything.
When broadcasting from Google Assistant App or by speech, it's working fine.

Turning lights on is working from the Sandbox, but broacasting isn't.
I see the broadcasting in Google My Activity, and the Assistant Relay is not giving any errors.
Could it be the problem that Hassio and the Assistant Relay are Running in Docker, so it's not the same network?
Any idea how to get this fixed? IPv6 is turned off in my DHCP server.

**Comment by Apipa169** [comment]
If you can see in in My Activity it means Assistant Relay is doing it's job. Do you have IPv6 enabled in your local network? That can cause this issue.

Hassio is always running in a Docker container, like this add-on. So that should not be the problem.

More info: https://assistantrelay.com/docs/other/faq#i-tried-a-broadcast-but-i-dont-hear-anything

**Comment by dheuts90** [comment]
> If you can see in in My Activity it means Assistant Relay is doing it's job. Do you have IPv6 enabled in your local network? That can cause this issue.
> 
> Hassio is always running in a Docker container, like this add-on. So that should not be the problem.
> 
> More info: https://assistantrelay.com/docs/other/faq#i-tried-a-broadcast-but-i-dont-hear-anything
Ok, strange. So it has to work this way..
Thanks a lot for your fast reply. Only seconds before you answered, I edited my post to say IPv6 is already turned off.

**Comment by Apipa169** [comment]
Do you have multiple subnets configured? Like a IoT network? 

Or an extra router behind your ISP-box? (if yes, is everything connected to the same router?)

Does broadcasting work by using the Google Assistant app?

**Comment by dheuts90** [comment]
Thanks for your fast response again. Broadcasting works by the Google Assistant app.

No, I only have 1 subnet, and only 1 modem/router. But I have a seperate DHCP server, DHCP is turned off on my modem/router. 

But I just saw I can turn off the DHCP v4 server on my modem, but for the IPv6 DHCP in the modem I can only choose stateless or stateful. When I check my Windows PC's, I only have a IPv4 address, but on my iPhone, I also see 2 IPv6 addresses.
So I will check with my ISP if it's possible to completely turn it off.

Otherwise I will ask them to put my modem in Bridge mode and put another router behind it.

**Comment by Apipa169** [comment]
I'm pretty sure that is the issue. Getting rid of the IPS's modem/router would have my personal preference if i were you.
