### ISSUE TITLE
Repository Structure Not Compliant

### ISSUE THREAD

**Issue by short4bmoney** [Apipa169/Assistant-Relay-for-Hassio#61]
**Describe the bug**
Upon adding via repository URL, I get an error `Repostitory structure for 0.7.4 is not compliant`

**Expected behavior**
Successful install of custom add-on through HACS

**System (please complete the following information):**
Hassio (supervisor?) version: 2020.12.7
Home Assistant version: 2020.12.2

**Additional context**
I'm selecting the type of add-on as _integration_ which I believe is a non-issue.

**Comment by Apipa169** [comment]
Its made for hassio, it won't work with HACS.
