### ISSUE TITLE
[supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated.

### ISSUE THREAD

**Issue by supergroover** [Apipa169/Assistant-Relay-for-Hassio#66]
**Describe the bug**
After the supervisor update version 2021.02.5

**To Reproduce**
1. restart supervisor
2. or reboot host

**Expected behavior**
No warnings or errors in my HomeAssistant log :)

**Screenshots**

**System (please complete the following information):**

Versie | core-2021.2.1
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Virtuele omgeving | false
Python versie | 3.8.7
Operating System Family | Linux

**Additional context**
Supervisor Log
````
21-02-08 10:44:21 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Assistant Relay BETA
21-02-08 10:44:21 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Assistant Relay
````

**Comment by archerne** [comment]
Can this be updated on the Beta branch as well? Thanks!

**Comment by FaserF** [comment]
> Can this be updated on the Beta branch as well? Thanks!

With my merge request above, the beta would be updated too. We only need to merge it.

**Comment by Apipa169** [comment]
Merged! But keep in mind I still need to create a release, which I will do later.

Thanks for the PR!

**Comment by Apipa169** [comment]
Never mind, a release is not required.
