### ISSUE TITLE
failing to send "play music" commands

### ISSUE THREAD

**Issue by TrommlerHH** [Apipa169/Assistant-Relay-for-Hassio#69]
Hi,

I would love to use this feature and installed properly according to Graysons youtube-video.

Until now I only checked the sandbox.

With broadcast commands it works, also with switching lights on and of.

But if I want to start music or radio I always get "sorry, I do not understand" or sometimes a response as if I asked for information, but not for playing music.

Is it because, this function is not able to send the command to a specific device?

**Comment by Apipa169** [comment]
Unfortunately that is a limitation of the Google SDK which is used by assistant relay.

**Comment by TrommlerHH** [comment]
What a pity! That was main my main purpose.

Any idea, how I could send the command to stream a radio station from a google device?

**Comment by iantrich** [comment]
The crude method I'm currently using is to use TTS to a secondary device located close to a Google device to vocalize my commands.

**Comment by TrommlerHH** [comment]
Lol! That is a very special workaround!

I tried it with the media_player.play_media-service like this, but it also failed:

entity_id: media_player.rikes_mini
media_content_id: ‘http://www.ndr.de/resources/metadaten/audio/aac/ndr2_hh.m3u’
media_content_type: music

Also with
media_content_type: audio/mp3 it won’t run.

Sorry for going completely off-topic here, but I do not know, where to post this topic.

**Comment by Apipa169** [comment]
@TrommlerHH I think it won't play because the address of the mp3 file is not https.

**Comment by TrommlerHH** [comment]
Ok, thanks!

The public radio-station offers the stream with less secure http, but the HA-service accepts only https?

That's weired.
