### ISSUE TITLE
about:blank page during setup

### ISSUE THREAD

**Issue by kentloving** [Apipa169/Assistant-Relay-for-Hassio#7]
**Describe the bug**
Not able to get past user setup step 2 page

**To Reproduce**
1. Install the add-on
2. open the web UI
3. follow set up instructions on Step 1 page, then click Next
4. enter a name and select the client secrets json file. Click Next

A new tab appears in the browser, title = about:blank, that has no content.

5. Close the about.blank tab

Now I get a Step 3 page where it is asking me for a authorization code for a token. I don’t know what to put there.

**Expected behavior**
I think that the ‘blank’ page should be a user consent page. I think that Google needs to get my consent before giving authorization. 

**System (please complete the following information):**
Hassio version: HassOS 2.12, Home Assistant 0.102.2
System: Rasperry Pi 3 b
I have tried using Chrome and Safari browsers on a Mac, and Chrome on an Android phone. I have enabled popups on all.

**Comment by Apipa169** [comment]
Looks like it is the same issue as reported in the Assistant Relay repository.

https://github.com/greghesp/assistant-relay/issues/138

Have you tried to disable the pop-up blocker of the browser before the setup? I had some issues with that when I did the set up for the first time.

**Comment by kentloving** [comment]
yes it does. 
BTW, On the page that asks for 'User' and the secrets file, do I enter my homeassistant user name, or the name that I entered in Google for the client ID, or maybe my username in Google?

**Comment by Apipa169** [comment]
The username can be anything you like. This name you should use when you send commands to Assistant Relay. In other words: use this name in the HA config.

The pop up which is blank now should be a page from google to login.

**Comment by Apipa169** [comment]
I have made a rollback to the previous release. This fixed the problem for me.

I am working on a new release without this bug.

**Comment by alexwohlbruck** [comment]
I am having this issue now, running 0.7.4 with AR v3.2.

**Comment by Apipa169** [comment]
@alexwohlbruck You might have downloaded the wrong auth file from Google.

**Comment by alexwohlbruck** [comment]
After reading the docs for the greghesp/assistant-relay, I see that I need to choose the TV/Limited input devices type when creating the OAuth credentials. I'm not sure if this was documented in the setup instructions.

**Comment by thomasbonte** [comment]
@alexwohlbruck Thanks for pointing to the "TV/Limited input devices type". That did the trick for me as well.
