### ISSUE TITLE
HACS --> "Repostitory structure for 0.7.4 is not compliant"

### ISSUE THREAD

**Issue by Milithor** [Apipa169/Assistant-Relay-for-Hassio#76]
**Describe the bug**
When I try to add custom integration repository in the HACS addon store: adding customer repo: https://github.com/Apipa169/Assistant-Relay-for-Hassio gives following error: "Repostitory structure for 0.7.4 is not compliant"

**To Reproduce**
1. Install HACS Addon Store (it's not natively installed with normal HA - non-hassio)
2. Go to 'HACS Sidebar'
2. Click on 'Integrations'
3. Click on 'menu top right (3 dots)'
4. Add URL "https://github.com/Apipa169/Assistant-Relay-for-Hassio" and 'integration' in drop down
5. See error: 'Repostitory structure for 0.7.4 is not compliant'

**Expected behavior**
A custom repo added where you can install your Assistant Relay Addon

**System (please complete the following information):**
HACS version: 1.11.3 - 20210214110032
HA version: Home Assistant 2021.2.3
System: Ubuntu 18.04

**Comment by Milithor** [comment]
I just saw that Hass.io is a requirement. Will install it in Docker.

**Comment by Apipa169** [comment]
This is made as Hassio addon and not compatible with HACS.
