### ISSUE TITLE
PL language

### ISSUE THREAD

**Issue by krzysiek2788** [Apipa169/Assistant-Relay-for-Hassio#83]
I do not see PL Language in Conversation list I need to enable it somewhere or it need to be implemented in the docker?

**Comment by Apipa169** [comment]
If it is not listed it is not supported by google. But most of the times it also works if you leave it on English.

**Comment by krzysiek2788** [comment]
PL lang is available in TTS option. So Broadcast will not work until google Home will add Polish language to allow command execution in this Lang, and it will be automatically added to Assistant Relay to select?
